name: Bundle size Base
on:
  push:
    branches: [master]

concurrency:
  # see https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle-size-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: npm
          node-version: 24.x

      - run: npm install

      - name: Build packages & create reports
        run: npm run bundle-size

      - name: Prepare report
        run: npx monosize upload-report --branch=master --commit-sha ${{ github.sha }} --report-files-glob="dist/bundle-size/monosize.json"

      - name: Upload report artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: monosize-report
          retention-days: 30
          if-no-files-found: error
          path: monosize-report.json
